version: '3.8'

services:

  web:
    container_name: web
    build: .
    working_dir: /src
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    depends_on:
      - postgres-fastapi

  postgres-fastapi:
    container_name: postgres-fastapi
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - ./.env
